### ISSUE TITLE
Questions about DrawerWorld

### ISSUE THREAD

**Issue by gemcollector** [TonyLianLong/VAI-ReinforcementLearning#1]
Hello～I wanna ask how to run code with DrawerWorld benchmark? How to adjust the parameters? Thx

**Comment by TonyLianLong** [comment]
Hi @gemcollector ,

To run DrawerWorld, you need to follow instructions in README.md to install it. It's basically a modification of MetaWorld that supports visual environments (original MetaWorld tasks are state-based so there is no visual environment for agents) with a few modifications to adjust the difficulty for pixel-based learning. However, despite the difference, the installation method is quite similar. If you have dependencies for drawerworld (e.g. mujoco), you could try:

```
cd src/env/drawerworld
pip install -e .
```

Then run code with domain name set to "metaworld". You can see more details in "env/wrappers.py" on how environments are switched.

The parameters can be adjusted with arguments to the command, and a list of them are in https://github.com/TonyLianLong/VAI-ReinforcementLearning/blob/main/src/arguments.py. Example commands are given in the README.md.

The hardest part is that, metaworld does not use the same mujoco python interface as DeepMind Control Suit. DrawerWorld/metaworld uses mujoco-py, but DeepMind Control Suit uses its own interface. Installing one does not mean that you can install the other. In addition, mujoco locations are different. We have found some servers that are able to install DMC only, DrawerWorld/MetaWorld only, and both, and I found that you need a NVIDIA driver that is close-sourced for GPU support. If you have issues on installation that does not seem to relate to visual rendering in the DrawerWorld (e.g. drivers/missing packages/GPU support), I recommend browsing the issues here: https://github.com/rlworkgroup/metaworld. However, if you do find issues with DrawerWorld, you can send us followup questions and we can investigate it.
