### ISSUE TITLE
Where can I find the Feature matching loss and reconstruction loss of Step 3?

### ISSUE THREAD

**Issue by dandelionhsc** [TonyLianLong/VAI-ReinforcementLearning#2]
Hi, I am struggling to find the feature matching loss and recon loss of step 3.
In 'agent.py', I could find the function 'update_inv_and_rewards', but 'update_reward' uses obs and next_obs, so I guess it is different from the loss mentioned in step 3.
Thank you! :)

**Comment by TonyLianLong** [comment]
Hi, the feature matching loss and reconstruction loss are to train the adapter, which is before RL training. https://github.com/TonyLianLong/VAI-ReinforcementLearning/blob/main/src/train_stage2.py#L687
