### ISSUE TITLE
Is foreground change applied to the observation in the current version?

### ISSUE THREAD

**Issue by wonheee** [TonyLianLong/VAI-ReinforcementLearning#4]
Hi, I'm interested in the idea, and when I compare your code with the paper, I find only background changes (random box, noise) are applied before getting into the encoder. Is foreground change applied in the current ver.? thanks:)

**Comment by TonyLianLong** [comment]
The foreground change is not applied on its own. The change which applies to foreground is the change that apples to the whole image (before adding background augmentations).

https://github.com/TonyLianLong/VAI-ReinforcementLearning/blob/f4d4dd668c3317f3d906c5e542a5912ccd74dce9/src/train_stage2.py#L439
