### ISSUE TITLE
Unable to find hyper parameter

### ISSUE THREAD

**Issue by munchmoo** [TonyLianLong/VAI-ReinforcementLearning#5]
Hi! In your paper, I can't find any hyperparameter used for experiment, even in you supplementary material.
Did you just used setting of PAD (policy adaptation during deployment)?
Thank you.

**Comment by TonyLianLong** [comment]
Yes. Our RL setting is the same as PAD. If you mean the hyperparams of training the encoder-decoder, it's in our source code (`task_info`).
