### ISSUE TITLE
How to use distracting environment with your code

### ISSUE THREAD

**Issue by MaryAhn** [TonyLianLong/VAI-ReinforcementLearning#7]
Hi, I want to run your code on distracting control suite environment (your paper table3) but it is not included in your environment.
How can I run your code on distracting benchmark?
Thank you :)

**Comment by TonyLianLong** [comment]
We use the official DM Control which is proposed by [PAD](https://github.com/nicklashansen/policy-adaptation-during-deployment). However, according to [here](https://github.com/nicklashansen/policy-adaptation-during-deployment/issues/8), the distraction setting is deprecated, and I do not recommend continuing to work on this setting. It seems that they proposed a [new benchmark](https://github.com/nicklashansen/dmcontrol-generalization-benchmark), which includes distraction setting as well. You can ask them about this new benchmark.
