### ISSUE TITLE
How to eval agent under DMC-GB distractions?

### ISSUE THREAD

**Issue by nuomizai** [TonyLianLong/VAI-ReinforcementLearning#8]
How do I evaluate the trained agent using the DMC-GB distractions shown in Figure 8 in the paper? I didn't found the related hyperparamter settings.

**Comment by TonyLianLong** [comment]
We use the official DM Control which is proposed by [PAD](https://github.com/nicklashansen/policy-adaptation-during-deployment). However, according to [the author's explanations](https://github.com/nicklashansen/policy-adaptation-during-deployment/issues/8), the distraction setting is deprecated, and I do not recommend continuing to work on this setting. It seems that they proposed a [new benchmark](https://github.com/nicklashansen/dmcontrol-generalization-benchmark), which includes distraction setting as well. You can run our models as the baseline as well as your models in this benchmark.

**Comment by nuomizai** [comment]
> We use the official DM Control which is proposed by [PAD](https://github.com/nicklashansen/policy-adaptation-during-deployment). However, according to [the author's explanations](https://github.com/nicklashansen/policy-adaptation-during-deployment/issues/8), the distraction setting is deprecated, and I do not recommend continuing to work on this setting. It seems that they proposed a [new benchmark](https://github.com/nicklashansen/dmcontrol-generalization-benchmark), which includes distraction setting as well. You can run our models as the baseline as well as your models in this benchmark.

Thanks for your reply. I'll check that!
